#  This file is part of Vidad.
#
#  Vidad is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Vidad is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Vidad.  If not, see <http://www.gnu.org/licenses/>.

	push	%eax
	mov	$0x00,%al
	jmp	handle_int

	push	%eax
	mov	$0x01,%al
	jmp	handle_int

	push	%eax
	mov	$0x02,%al
	jmp	handle_int

	push	%eax
	mov	$0x03,%al
	jmp	handle_int

	push	%eax
	mov	$0x04,%al
	jmp	handle_int

	push	%eax
	mov	$0x05,%al
	jmp	handle_int

	push	%eax
	mov	$0x06,%al
	jmp	handle_int

	push	%eax
	mov	$0x07,%al
	jmp	handle_int

	push	%eax
	mov	$0x08,%al
	jmp	handle_int

	push	%eax
	mov	$0x09,%al
	jmp	handle_int

	push	%eax
	mov	$0x0A,%al
	jmp	handle_int

	push	%eax
	mov	$0x0B,%al
	jmp	handle_int

	push	%eax
	mov	$0x0C,%al
	jmp	handle_int

	push	%eax
	mov	$0x0D,%al
	jmp	handle_int

	push	%eax
	mov	$0x0E,%al
	jmp	handle_int

	push	%eax
	mov	$0x0F,%al
	jmp	handle_int

	push	%eax
	mov	$0x10,%al
	jmp	handle_int

	push	%eax
	mov	$0x11,%al
	jmp	handle_int

	push	%eax
	mov	$0x12,%al
	jmp	handle_int

	push	%eax
	mov	$0x13,%al
	jmp	handle_int

	push	%eax
	mov	$0x14,%al
	jmp	handle_int

	push	%eax
	mov	$0x15,%al
	jmp	handle_int

	push	%eax
	mov	$0x16,%al
	jmp	handle_int

	push	%eax
	mov	$0x17,%al
	jmp	handle_int

	push	%eax
	mov	$0x18,%al
	jmp	handle_int

	push	%eax
	mov	$0x19,%al
	jmp	handle_int

	push	%eax
	mov	$0x1A,%al
	jmp	handle_int

	push	%eax
	mov	$0x1B,%al
	jmp	handle_int

	push	%eax
	mov	$0x1C,%al
	jmp	handle_int

	push	%eax
	mov	$0x1D,%al
	jmp	handle_int

	push	%eax
	mov	$0x1E,%al
	jmp	handle_int

	push	%eax
	mov	$0x1F,%al
	jmp	handle_int

	push	%eax
	mov	$0x20,%al
	jmp	handle_int

	push	%eax
	mov	$0x21,%al
	jmp	handle_int

	push	%eax
	mov	$0x22,%al
	jmp	handle_int

	push	%eax
	mov	$0x23,%al
	jmp	handle_int

	push	%eax
	mov	$0x24,%al
	jmp	handle_int

	push	%eax
	mov	$0x25,%al
	jmp	handle_int

	push	%eax
	mov	$0x26,%al
	jmp	handle_int

	push	%eax
	mov	$0x27,%al
	jmp	handle_int

	push	%eax
	mov	$0x28,%al
	jmp	handle_int

	push	%eax
	mov	$0x29,%al
	jmp	handle_int

	push	%eax
	mov	$0x2A,%al
	jmp	handle_int

	push	%eax
	mov	$0x2B,%al
	jmp	handle_int

	push	%eax
	mov	$0x2C,%al
	jmp	handle_int

	push	%eax
	mov	$0x2D,%al
	jmp	handle_int

	push	%eax
	mov	$0x2E,%al
	jmp	handle_int

	push	%eax
	mov	$0x2F,%al
	jmp	handle_int

	push	%eax
	mov	$0x30,%al
	jmp	handle_int

	push	%eax
	mov	$0x31,%al
	jmp	handle_int

	push	%eax
	mov	$0x32,%al
	jmp	handle_int

	push	%eax
	mov	$0x33,%al
	jmp	handle_int

	push	%eax
	mov	$0x34,%al
	jmp	handle_int

	push	%eax
	mov	$0x35,%al
	jmp	handle_int

	push	%eax
	mov	$0x36,%al
	jmp	handle_int

	push	%eax
	mov	$0x37,%al
	jmp	handle_int

	push	%eax
	mov	$0x38,%al
	jmp	handle_int

	push	%eax
	mov	$0x39,%al
	jmp	handle_int

	push	%eax
	mov	$0x3A,%al
	jmp	handle_int

	push	%eax
	mov	$0x3B,%al
	jmp	handle_int

	push	%eax
	mov	$0x3C,%al
	jmp	handle_int

	push	%eax
	mov	$0x3D,%al
	jmp	handle_int

	push	%eax
	mov	$0x3E,%al
	jmp	handle_int

	push	%eax
	mov	$0x3F,%al
	jmp	handle_int
