loader = Environment()
loader.Replace(LINK = "/usr/local/cross/bin/i486-elf-ld")
loader.Replace(AS = "/usr/local/cross/bin/i486-elf-as")
loader.Replace(CC = "/usr/local/cross/bin/i486-elf-gcc")
loader.Replace(CCFLAGS = "-Wall -Wextra -Werror -nostdlib -fno-builtin -nostartfiles -nodefaultlibs -Os -std=gnu99")


multiboot = loader.Clone()
multiboot.Replace(LINKFLAGS = "-T multiboot.ld")
multiboot.Program("multiboot.binx", ["multiboot.s", "loader_print.c", "mb_data.c"])
multiboot.Depends("multiboot.binx", "multiboot.ld")
multiboot.Command("multiboot.bin", "multiboot.binx", "chmod -x multiboot.binx && cp multiboot.binx multiboot.bin")


boot_block = loader.Clone()
boot_block.Replace(LINKFLAGS = "-T boot_block.ld")
boot_block.Program("boot_block.binx", ["boot_block.s", "loader_print.c", "loader.c"])
boot_block.Depends("boot_block.binx", "boot_block.ld")
boot_block.Command("boot_block.bin", "boot_block.binx", "chmod -x boot_block.binx && cp boot_block.binx boot_block.bin")

loader.Command("multboot.bin", "multiboot.bin", \
	"cp boot_block.bin multboot.bin && dd if=multiboot.bin of=multboot.bin seek=8")
loader.Depends("multboot.bin", "boot_block.bin")
