loader = Environment()
loader.Replace(LINK = "/usr/local/cross/bin/i486-elf-ld")
loader.Replace(AS = "/usr/local/cross/bin/i486-elf-as")
loader.Replace(CC = "/usr/local/cross/bin/i486-elf-gcc")
loader.Replace(CCFLAGS = "-Wall -Wextra -Werror -nostdlib -fno-builtin -nostartfiles -nodefaultlibs -Os -std=gnu99")



boot_sect = loader.Clone()
boot_sect.Replace(LINKFLAGS = "-T boot_sect.ld")
boot_sect.Program("boot_sect.tmpx", ["boot_sect.s"])
boot_sect.Depends("boot_sect.tmpx", "boot_sect.ld")
boot_sect.Command("boot_sect.tmp", "boot_sect.tmpx", "chmod -x boot_sect.tmpx && cp boot_sect.tmpx boot_sect.tmp")


boot_block = loader.Clone()
boot_block.Replace(LINKFLAGS = "-T boot_block.ld")
boot_block.Program("boot_block.tmpx", ["boot_block.s", "loader_hw.c", "loader_m.c"])
boot_block.Depends("boot_block.tmpx", "boot_block.ld")
boot_block.Command("boot_block.tmp", "boot_block.tmpx", "chmod -x boot_block.tmpx && cp boot_block.tmpx boot_block.tmp")

boot_block.Command("boot_block.bin", "boot_block.tmp", \
	"cp boot_sect.tmp boot_block.bin && dd if=boot_block.tmp of=boot_block.bin seek=1")
boot_block.Depends("boot_block.bin", "boot_sect.tmp")



#page_init = loader.Clone()
#page_init.Replace(LINKFLAGS = "-T page_init.ld")
#page_init.Program("page_init.binx", ["kheader.s", "page_init.c"])
#page_init.Depends("page_init.binx", "page_init.ld")
#page_init.Command("page_init.bin", "page_init.binx", "chmod -x page_init.binx && cp page_init.binx page_init.bin")
